/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CloneFileOptions {
  noFollow?: boolean
  noOwnerCopy?: boolean
  cloneAcl?: boolean
}
export function cloneFileSync(src: string, dst: string, options?: CloneFileOptions | undefined | null): number
export function cloneFile(src: string, dst: string, options?: CloneFileOptions | undefined | null): Promise<number>
