/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function cloneFileSync(src: string, dst: string): number
export function cloneFile(src: string, dst: string): Promise<number>
