/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function cloneFile(src: string, dst: string, options?: CloneFileOptions | undefined | null): Promise<number>

export interface CloneFileOptions {
  noFollow?: boolean
  noOwnerCopy?: boolean
  cloneAcl?: boolean
}

export declare function cloneFileSync(src: string, dst: string, options?: CloneFileOptions | undefined | null): number
